name: Run CI Tests

on:
  pull_request:

jobs:
  run-test:
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Checks with pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Test with pytest
        run: |
          python -m pip install .
          python -m pytest
